name: financial_chart
description: A chart library for financial data. supports candlestick, ohlc, line, area, bar charts and custom chart types.
repository: https://github.com/cjjapan/financial_chart
issue_tracker: https://github.com/cjjapan/financial_chart/issues
homepage: https://github.com/cjjapan/financial_chart
topics:
  - chart
  - charts
  - graph
  - candlestick
  - stock
# publish_to: "none"

version: 0.3.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lints: ^2.1.1

flutter:
  uses-material-design: true
