name: financial_chart
description: A chart library for financial data. supports candlestick, ohlc, line, area, bar charts and custom chart types.
repository: https://github.com/cjjapan/financial_chart
issue_tracker: https://github.com/cjjapan/financial_chart/issues
homepage: https://cjjapan.github.io/financial_chart_docs/
documentation: https://cjjapan.github.io/financial_chart_docs/
topics:
  - chart
  - graph
  - candlestick
  - stock
# publish_to: "none"

version: 0.3.4

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
